### ISSUE TITLE
Update required to support 1.16.5

### ISSUE THREAD

**Issue by Vidhin05** [andyvanee/hscroll#6]
Don't see 1.16.5 on the releases page. Can this be updated?

**Comment by SB2DD** [comment]
Could 1.17 be supported too ?

**Comment by hamarb123** [comment]
Please update this @andyvanee. Any ideas as to what the cause of it not working is?

**Comment by andyvanee** [comment]
As [I mentioned here](https://github.com/andyvanee/hscroll/pull/7#issuecomment-1076909134) I don't really have any interest in long-term maintenance of this project, since it was really just a proof-of-concept. Building and testing for new versions is not generally big deal but it is not trivial either.

If someone is interested in putting the time into building/maintaining for future versions, I'll be happy to link to their fork or give access.
